### ISSUE TITLE
Please implement the -o OrgID option properly?

### ISSUE THREAD

**Issue by jmboby** [RedHatSatellite/sat6Inventory#16]
Any chance you could update this script so the -o OrgID actually limits the report to the specific OrgID?, at present it just seems to change the output file name (which is handy) but it still includes all registered client workloads from all Orgs.

Redhat are asking us to report back on usage per client and since there is no reporting feature in Satellite 6.1 I am using this tool....which is great except for this missing feature.

Cheers
James

**Comment by evgeni** [comment]
@jmboby can you please try the patch from https://github.com/RedHatSatellite/sat6Inventory/pull/18 if that fixes the issue for you?

**Comment by jmboby** [comment]
Excellent - that worked a treat. Org's all reporting correctly now.

Thanks guys.

James Wilson
