### ISSUE TITLE
RFE: Add virtual guest count to Hypervisor report type

### ISSUE THREAD

**Issue by gocyclones** [RedHatSatellite/sat6Inventory#23]
Looking to add a virtual guest count to the hypervisor report.  This will help me determine where it is best to use my VDC subs versus individual subs for guests since we have a mix.  This should be able to come from the virtual_guests in sysdata I believe.  Similar to what is done for Errata counts.

**Comment by evgeni** [comment]
hey, please test and verify https://github.com/RedHatSatellite/sat6Inventory/pull/25 :)

**Comment by gocyclones** [comment]
Tested and confirmed that it works as expected.  Thanks! I created a hypervisor format:
`'hypervisor': ['hostname', 'entitlements', 'num_virtual_guests', 'amount', 'account_number', 'contract_number', 'virtual', 'cores']`

**Comment by sideangleside** [comment]
+1 on my testing as well.
