### ISSUE TITLE
Issue: Content hosts with multiple subscriptions only show the first sub in report

### ISSUE THREAD

**Issue by gocyclones** [RedHatSatellite/sat6Inventory#24]
When running a report systems with multiple subs (like EPEL, MyCompany Repo, and Red Hat VDC) will only show the first listed sub.  This is because that is all that is presented in the json output from the API.  When you use the newer API in 6.2+ it actually shows all 3 available.  Something like this shows all 3: https://sat6.example.com/api/hosts/207/subscriptions/
`[{"quantity_consumed":1,"id":48,"cp_id":"2203a0f0587a148901589292a0396881","subscription_id":11,"name":"Red Hat Enterprise Linux for Virtual Datacenters with Smart Management, Premium","start_date":"2015-07-01T04:00:00.000+0000","end_date":"2018-07-01T03:59:59.000+0000","available":-17,"quantity":-1,"consumed":16,"account_number":678902,"contract_number":XXXXXXX,"support_level":"Premium","product_id":"RH00006S","sockets":2,"cores":null,"ram":null,"instance_multiplier":1,"stacking_id":0,"multi_entitlement":true,"type":"STACK_DERIVED","product_name":"Red Hat Enterprise Linux for Virtual Datacenters with Smart Management, Premium","unmapped_guest":false,"virt_only":true,"virt_who":false,"host":{"id":1800,"name":"virt-who-host1.example.com-3"}},{"quantity_consumed":1,"id":7,"cp_id":"2203a0f057ff1b1e01584040bb4857c6","subscription_id":32,"name":"MyCompany Repo","start_date":"2016-11-07T19:25:32.000+0000","end_date":"2046-10-31T19:25:32.000+0000","available":-1437,"quantity":-1,"consumed":1436,"account_number":null,"contract_number":null,"support_level":null,"product_id":"1478546732191","sockets":null,"cores":null,"ram":null,"instance_multiplier":1,"stacking_id":null,"multi_entitlement":null,"type":"NORMAL","product_name":"MyCompany Repo","unmapped_guest":false,"virt_only":false,"virt_who":false},{"quantity_consumed":1,"id":98,"cp_id":"2203a0f04b9877cc014b9ded012c0078","subscription_id":30,"name":"EPEL","start_date":"2015-02-18T18:22:10.000+0000","end_date":"2045-02-10T18:22:10.000+0000","available":-151,"quantity":-1,"consumed":150,"account_number":null,"contract_number":null,"support_level":null,"product_id":"1424283729978","sockets":null,"cores":null,"ram":null,"instance_multiplier":1,"stacking_id":null,"multi_entitlement":null,"type":"NORMAL","product_name":"EPEL","unmapped_guest":false,"virt_only":false,"virt_who":false}]}
`
When I show the json output I get this: 

```
[root@sat6 sat6_Inventory]# ./sat6Inventory.py -l XXXXXX -p XXXXXX -s sat6.example.com -o EXAMPLE --format=original -S system1 -d
[DEBUG] LOGIN -> XXXXXXX
[DEBUG] PASSWORD -> XXXXXXX
[DEBUG] SATELLITE -> sat6.example.com
[DEBUG] ORG ID -> EXAMPLE
================================================================================
[VERBOSE] Connecting to -> https://sat6.example.com/api/status
================================================================================
[VERBOSE] API Version -> 2
================================================================================
[VERBOSE] Connecting to -> https://sat6.example.com/katello/api/v2/systems?page=1&per_page=100&search=system1
[VERBOSE] Data will be written to EXAMPLE_inventory_report.csv
================================================================================
[VERBOSE] Connecting to -> https://sat6.example.com/katello/api/v2/systems/383d7427-2905-4d26-9bcb-5f35b8d6bd8b?fields=full
[VERBOSE] Connecting to -> https://sat6.example.com/api/v2/hosts/207/subscriptions
[VERBOSE] Connecting to -> https://sat6.example.com/api/v2/hosts/system1/facts?per_page=99999
[DEBUG] System output in -> EXAMPLE_383d7427-2905-4d26-9bcb-5f35b8d6bd8b_system-output.json
[DEBUG] Subscription output in -> EXAMPLE_383d7427-2905-4d26-9bcb-5f35b8d6bd8b_subscription-output.json
[DEBUG] Facts output in -> EXAMPLE_383d7427-2905-4d26-9bcb-5f35b8d6bd8b_system-facts.json
{
  "biosversion": "unknown",
  "ipv6_address": "::1",
  "system_group": "unknown",
  "ip_addresses": "192.168.1.100",
  "serialnumber": "unknown",
  "memorysize": "unknown",
  "hardware": "2 CPUs 2 Sockets",
  "operatingsystem": "unknown",
  "boardproductname": "unknown",
  "uuid": "383d7427-2905-4d26-9bcb-5f35b8d6bd8b",
  "entitlement": "EPEL",
  "systype": "unknown",
  "hostname": "system1",
  "amount": 1,
  "virtual": "virtual",
  "last_checkin_time": "2016-12-21 15:40:16 +0000",
  "boardmanufacturer": "unknown",
  "start_date": "2015-02-18T18:22:10.000+0000",
  "virt_type": "vmware",
  "entitlements": "EPEL",
  "virtual_host_name": "host1.example.com",
  "contract_number": null,
  "account_number": null,
  "osfamily": "unknown",
  "is_virtualized": "true",
  "end_date": "2045-02-10T18:22:10.000+0000",
  "registered_by": null,
  "errata_out_of_date": 0,
  "num_sockets": "2",
  "biosreleasedate": "unknown",
  "ipv6_addresses": "",
  "packages_out_of_date": 0,
  "systemuuid": "unknown",
  "compliant": true,
  "ip_address": "162.131.217.245",
  "manufacturer": "unknown",
  "software_channel": "unknown",
  "organization": "PFG",
  "boardserialnumber": "unknown",
  "configuration_channel": "unknown",
  "registration_time": "2016-04-27T09:35:46.242+0000",
  "hypervisor": "NA",
  "biosvendor": "unknown",
  "productname": "unknown",
  "kernel_version": "2.6.32-642.15.1.el6.x86_64",
  "katello_agent_installed": true,
  "architecture": "x86_64",
  "virtual_host": "cea82424-39b5-4dde-8e8e-d88eeb0e2187",
  "cores": "2"
}
================================================================================


Subscription Usage Summary:
EPEL -->
        NA      - 1
```

**Comment by sideangleside** [comment]
Looking at the API calls in this output, You are using an older version of this script, which provided incorrect data on 6.2 Satellites. This was addressed with #20. Can you attempt to reproduce on the latest from git (or anything committed after #20 was merged)

**Comment by gocyclones** [comment]
Yep you are correct.  This is fixed with the latest updates.

**Comment by evgeni** [comment]
closing then, thanks for testing
